package dekun.wang.markdown.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import dekun.wang.markdown.settings.model.PluginSettingsStateBo;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author wdk
 * &#064;date  2023/4/18 00:34  星期二
 * @see <a href=""></a>
 * <br>
 */
public class PluginSettingForm {

    private JPanel settingPanel;
    private JTextField installPath;
    private JButton commit;

    public PluginSettingsStateBo getSettingsState() {
        return new PluginSettingsStateBo (installPath.getText ());
    }

    public void getSettingState(PluginSettingsStateBo stateBo) {
        installPath.setText (stateBo.getFavoriteMarkdown ());
    }


    public JPanel getSettingPanel() {
        return settingPanel;
    }

    public JTextField getInstallPath() {
        return installPath;
    }

    public JButton getCommit() {
        return commit;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$ ();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        settingPanel = new JPanel ();
        settingPanel.setLayout (new GridLayoutManager (2, 3, new Insets (0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel ();
        label1.setText ("Typora安装位置");
        settingPanel.add (label1, new GridConstraints (0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer ();
        settingPanel.add (spacer1, new GridConstraints (1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        installPath = new JTextField ();
        installPath.setText ("");
        settingPanel.add (installPath, new GridConstraints (0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension (100, -1), null, 0, false));
        commit = new JButton ();
        commit.setText ("....");
        settingPanel.add (commit, new GridConstraints (0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return settingPanel;
    }
}
